
const map = [
  {
    name:'安徽',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/anhui.png'
  },
  {
    name:'澳门',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/aomen.png'
  },
  {
    name:'北京',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/beijing.png'
  },
  {
    name:'重庆',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/chongqing.png'
  },
  {
    name:'福建',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/fujian.png'
  },
  {
    name:'甘肃',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/gansu.png'
  },
  {
    name:'广东',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/guangdong.png'
  },
  {
    name:'广西',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/guangxi.png'
  },
  {
    name:'贵州',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/guizhou.png'
  },
  {
    name:'海南',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/hainan.png'
  },
  {
    name:'河北',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/hebei.png'
  },
  {
    name:'河南',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/henan.png'
  },
  {
    name:'黑龙江',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/heilongjiang.png'
  },
  {
    name:'湖北',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/hubei.png'
  },
  {
    name:'湖南',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/hunan.png'
  },
  {
    name:'江苏',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/jiangsu.png'
  },
  {
    name:'江西',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/jiangxi.png'
  },
  {
    name:'吉林',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/jilin.png'
  },
  {
    name:'辽宁',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/liaoning.png'
  },
  {
    name:'内蒙古',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/neimenggu.png'
  },
  {
    name:'宁夏',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/ningxia.png'
  },
  {
    name:'青海',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/qinghai.png'
  },
  {
    name:'山东',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/shandong.png'
  },
  {
    name:'上海',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/shanghai.png'
  },
  {
    name:'山西',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/shanxi.png'
  },
  {
    name:'陕西',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/shanxi_.png'
  },
  {
    name:'四川',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/sichuan.png'
  },
  {
    name:'台湾',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/taiwan.png'
  },
  {
    name:'天津',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/tianjin.png'
  },
  {
    name:'香港',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/xianggang.png'
  },
  {
    name:'新疆',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/xinjiang.png'
  },
  {
    name:'西藏',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/xizang.png'
  },
  {
    name:'云南',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/yunnan.png'
  },
  {
    name:'浙江',
    url:'http://boweisou.oss-cn-shenzhen.aliyuncs.com/5G/zhejiang.png'
  },
  
]



module.exports = {
  map
}